"""User image false nullable.

Revision ID: 04e0541176a0
Revises: 8cbc02eab036
Create Date: 2020-06-05 20:01:53.920655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04e0541176a0'
down_revision = '8cbc02eab036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_image',
               existing_type=mysql.VARCHAR(length=41),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_image',
               existing_type=mysql.VARCHAR(length=41),
               nullable=True)
    # ### end Alembic commands ###
