"""Added info fields to Public Place.

Revision ID: 12a754d14b2f
Revises: a9f0869fcda4
Create Date: 2020-05-05 16:00:37.649506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12a754d14b2f'
down_revision = 'a9f0869fcda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_label', sa.String(length=30), nullable=False))
    op.drop_column('category', 'category_alias')
    op.add_column('public_place', sa.Column('public_place_avg_bill_id', sa.String(length=50), nullable=True))
    op.add_column('public_place', sa.Column('public_place_phone_number', sa.String(length=15), nullable=True))
    op.add_column('public_place', sa.Column('public_place_site', sa.String(length=100), nullable=True))
    op.add_column('public_place', sa.Column('public_place_visit_cost_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'public_place', 'locale_string', ['public_place_avg_bill_id'], ['string_id'])
    op.create_foreign_key(None, 'public_place', 'locale_string', ['public_place_visit_cost_id'], ['string_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_place', type_='foreignkey')
    op.drop_constraint(None, 'public_place', type_='foreignkey')
    op.drop_column('public_place', 'public_place_visit_cost_id')
    op.drop_column('public_place', 'public_place_site')
    op.drop_column('public_place', 'public_place_phone_number')
    op.drop_column('public_place', 'public_place_avg_bill_id')
    op.add_column('category', sa.Column('category_alias', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('category', 'category_label')
    # ### end Alembic commands ###
