"""empty message

Revision ID: 131cb6765c7a
Revises: f86f9d2edc79
Create Date: 2020-02-26 21:51:36.844766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '131cb6765c7a'
down_revision = 'f86f9d2edc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('admin', 'moder', 'user', name='rolename'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_name',
               existing_type=sa.Enum('admin', 'moder', 'user', name='rolename'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
