"""Favorites update and user image.

Revision ID: 17d26b38187b
Revises: 0bab6544b4d8
Create Date: 2020-03-22 20:14:10.583858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17d26b38187b'
down_revision = '0bab6544b4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='cascade')
    )
    op.create_index(op.f('ix_user_favorite_entity_id'), 'user_favorite', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_user_id'), 'user_favorite', ['user_id'], unique=False)
    op.drop_table('user_favorite_place')
    op.add_column('user', sa.Column('user_image', sa.String(length=41), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_image')
    op.create_table('user_favorite_place',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('place_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('add_time', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.object_id'], name='user_favorite_place_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_favorite_place_ibfk_2', ondelete='CASCADE'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_favorite_place_user_id', 'user_favorite_place', ['user_id'], unique=False)
    op.create_index('ix_user_favorite_place_place_id', 'user_favorite_place', ['place_id'], unique=False)
    op.drop_index(op.f('ix_user_favorite_user_id'), table_name='user_favorite')
    op.drop_index(op.f('ix_user_favorite_entity_id'), table_name='user_favorite')
    op.drop_table('user_favorite')
    # ### end Alembic commands ###
