"""Move city to entity.

Revision ID: 18b4ab72ccab
Revises: 17d26b38187b
Create Date: 2020-04-13 03:28:14.723852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.

revision = '18b4ab72ccab'
down_revision = '17d26b38187b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('entity_city_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'entity', 'city', ['entity_city_id'], ['city_id'])
    op.drop_constraint('object_ibfk_5', 'object', type_='foreignkey')
    op.drop_column('object', 'object_city_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('object_city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('object_ibfk_1', 'object', 'city', ['object_city_id'], ['city_id'])
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.drop_column('entity', 'entity_city_id')
    # ### end Alembic commands ###
