"""Added admin role.

Revision ID: 444e2014db70
Revises: 04e0541176a0
Create Date: 2020-06-08 01:40:07.443297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '444e2014db70'
down_revision = '04e0541176a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_name',
               existing_type=mysql.ENUM('content_moder', 'user_moder', 'user'),
               type_=sa.Enum('admin', 'content_moder', 'user_moder', 'user', name='rolename'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_name',
               existing_type=sa.Enum('admin', 'content_moder', 'user_moder', 'user', name='rolename'),
               type_=mysql.ENUM('content_moder', 'user_moder', 'user'),
               existing_nullable=False)
    # ### end Alembic commands ###
