"""Added info fields to Public Place.

Revision ID: 697a104697a9
Revises: a9f0869fcda4
Create Date: 2020-05-03 19:21:17.071186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697a104697a9'
down_revision = 'a9f0869fcda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_place', sa.Column('public_place_avg_check', sa.String(length=50), nullable=True))
    op.add_column('public_place', sa.Column('public_place_food_id', sa.String(length=50), nullable=True))
    op.add_column('public_place', sa.Column('public_place_phone', sa.String(length=15), nullable=True))
    op.add_column('public_place', sa.Column('public_place_site', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'public_place', 'locale_string', ['public_place_food_id'], ['string_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'public_place', type_='foreignkey')
    op.drop_column('public_place', 'public_place_site')
    op.drop_column('public_place', 'public_place_phone')
    op.drop_column('public_place', 'public_place_food_id')
    op.drop_column('public_place', 'public_place_avg_check')
    # ### end Alembic commands ###
