"""Admin role deleted.

Revision ID: 6afad1dfb13b
Revises: c96cb681887a
Create Date: 2020-02-29 00:17:41.364511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6afad1dfb13b'
down_revision = 'c96cb681887a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_name',
               existing_type=mysql.ENUM('admin', 'content_moder', 'user_moder', 'user'),
               type_=sa.Enum('content_moder', 'user_moder', 'user', name='rolename'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_name',
               existing_type=sa.Enum('content_moder', 'user_moder', 'user', name='rolename'),
               type_=mysql.ENUM('admin', 'content_moder', 'user_moder', 'user'),
               existing_nullable=False)
    # ### end Alembic commands ###
