"""Added locale to review.

Revision ID: 8cbc02eab036
Revises: e9253b3efeed
Create Date: 2020-06-04 15:34:09.999674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbc02eab036'
down_revision = 'e9253b3efeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review_locale', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'review_locale')
    # ### end Alembic commands ###
