"""Initial migration

Revision ID: a9f0869fcda4
Revises: 
Create Date: 2020-04-25 11:53:13.460917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f0869fcda4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocation',
    sa.Column('geolocation_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('geolocation_id')
    )
    op.create_table('locale_link',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('link_locale', sa.Enum('ru', 'en', name='language'), nullable=False),
    sa.Column('link_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('link_id', 'link_locale')
    )
    op.create_table('locale_string',
    sa.Column('string_id', sa.String(length=36), nullable=False),
    sa.Column('string_locale', sa.Enum('ru', 'en', name='language'), nullable=False),
    sa.Column('string_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('string_id', 'string_locale')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.Enum('content_moder', 'user_moder', 'user', name='rolename'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_password', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('user_image', sa.String(length=41), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_alias', sa.String(length=30), nullable=False),
    sa.Column('category_name_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_name_id'], ['locale_string.string_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city_name_id', sa.String(length=36), nullable=False),
    sa.Column('city_image_link', sa.String(length=250), nullable=False),
    sa.Column('city_description_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['city_description_id'], ['locale_string.string_id'], ),
    sa.ForeignKeyConstraint(['city_name_id'], ['locale_string.string_id'], ),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('entity',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('entity', 'object', 'place', 'public_place', 'historical_person', 'route', name='entitytype'), nullable=False),
    sa.Column('entity_city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_city_id'], ['city.city_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('object',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('object_image_link', sa.String(length=250), nullable=False),
    sa.Column('object_audioguide_link_id', sa.String(length=36), nullable=True),
    sa.Column('object_description_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['object_audioguide_link_id'], ['locale_link.link_id'], ),
    sa.ForeignKeyConstraint(['object_description_id'], ['locale_string.string_id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['entity.entity_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('review',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('review_rating', sa.SMALLINT(), nullable=False),
    sa.Column('review_time', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'entity_id')
    )
    op.create_table('route',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('route_name_id', sa.String(length=36), nullable=False),
    sa.Column('route_description_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['route_description_id'], ['locale_string.string_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['entity.entity_id'], ),
    sa.ForeignKeyConstraint(['route_name_id'], ['locale_string.string_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('user_favorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.entity_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='cascade')
    )
    op.create_index(op.f('ix_user_favorite_entity_id'), 'user_favorite', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_user_id'), 'user_favorite', ['user_id'], unique=False)
    op.create_table('category_object',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['object_id'], ['object.object_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('object_id', 'category_id')
    )
    op.create_table('historical_person',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('person_name_id', sa.String(length=36), nullable=False),
    sa.Column('person_second_name_id', sa.String(length=36), nullable=False),
    sa.Column('person_patronymic_id', sa.String(length=36), nullable=True),
    sa.Column('person_birthdate', sa.Date(), nullable=False),
    sa.Column('person_deathdate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['object.object_id'], ),
    sa.ForeignKeyConstraint(['person_name_id'], ['locale_string.string_id'], ),
    sa.ForeignKeyConstraint(['person_patronymic_id'], ['locale_string.string_id'], ),
    sa.ForeignKeyConstraint(['person_second_name_id'], ['locale_string.string_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('place',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('place_name_id', sa.String(length=36), nullable=False),
    sa.Column('place_address_id', sa.String(length=36), nullable=False),
    sa.Column('place_geolocation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['object.object_id'], ),
    sa.ForeignKeyConstraint(['place_address_id'], ['locale_string.string_id'], ),
    sa.ForeignKeyConstraint(['place_geolocation_id'], ['geolocation.geolocation_id'], ),
    sa.ForeignKeyConstraint(['place_name_id'], ['locale_string.string_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('historical_person_related_objects',
    sa.Column('historical_person_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['historical_person_id'], ['historical_person.object_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['object_id'], ['object.object_id'], ondelete='cascade')
    )
    op.create_table('public_place',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['place.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('route_place_info',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('route_place_order', sa.Integer(), nullable=False),
    sa.Column('route_place_description_id', sa.String(length=36), nullable=True),
    sa.Column('route_place_audioguide_link_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.object_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ),
    sa.ForeignKeyConstraint(['route_place_audioguide_link_id'], ['locale_link.link_id'], ),
    sa.ForeignKeyConstraint(['route_place_description_id'], ['locale_string.string_id'], ),
    sa.PrimaryKeyConstraint('place_id', 'route_id')
    )
    op.create_table('timetable',
    sa.Column('public_place_id', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='weekday'), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['public_place_id'], ['public_place.object_id'], ),
    sa.PrimaryKeyConstraint('public_place_id', 'week_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    op.drop_table('route_place_info')
    op.drop_table('public_place')
    op.drop_table('historical_person_related_objects')
    op.drop_table('place')
    op.drop_table('historical_person')
    op.drop_table('category_object')
    op.drop_index(op.f('ix_user_favorite_user_id'), table_name='user_favorite')
    op.drop_index(op.f('ix_user_favorite_entity_id'), table_name='user_favorite')
    op.drop_table('user_favorite')
    op.drop_table('route')
    op.drop_table('review')
    op.drop_table('object')
    op.drop_table('entity')
    op.drop_table('user_role')
    op.drop_table('city')
    op.drop_table('category')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('locale_string')
    op.drop_table('locale_link')
    op.drop_table('geolocation')
    # ### end Alembic commands ###
