"""role.role_name changed to enum.

Revision ID: cb398cf84fc1
Revises: f86f9d2edc79
Create Date: 2020-02-27 15:15:54.080211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb398cf84fc1'
down_revision = 'f86f9d2edc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('admin', 'moder', 'user', name='rolename'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'role_name',
               existing_type=sa.Enum('admin', 'moder', 'user', name='rolename'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
