"""Added user visited places.

Revision ID: e9253b3efeed
Revises: 12a754d14b2f
Create Date: 2020-05-14 13:01:58.077493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9253b3efeed'
down_revision = '12a754d14b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_visited_place',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
    sa.ForeignKeyConstraint(['place_id'], ['place.object_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='cascade')
    )
    op.create_index(op.f('ix_user_visited_place_place_id'), 'user_visited_place', ['place_id'], unique=False)
    op.create_index(op.f('ix_user_visited_place_user_id'), 'user_visited_place', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_visited_place_user_id'), table_name='user_visited_place')
    op.drop_index(op.f('ix_user_visited_place_place_id'), table_name='user_visited_place')
    op.drop_table('user_visited_place')
    # ### end Alembic commands ###
