"""Added aliases of categories.

Revision ID: ea5ad7587c7f
Revises: f467ff99202e
Create Date: 2020-03-20 16:04:46.594379

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision = 'ea5ad7587c7f'
down_revision = 'f467ff99202e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_alias', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'category_alias')
    # ### end Alembic commands ###
