"""Added aliases of categories.

Revision ID: ea5ad7587c7f
Revises: f467ff99202e
Create Date: 2020-03-20 16:04:46.594379

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from migrations.util.add_field_data import add_field_data
from models.Category import Category

revision = 'ea5ad7587c7f'
down_revision = 'f467ff99202e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column('category', sa.Column('category_alias', sa.String(length=30), nullable=False))
    op.create_foreign_key(None, 'place', 'locale_string', ['place_name_id'], ['string_id'])

    add_field_data(conn, Category.__table__, 'category_id', 1, 'category_alias', 'monuments')
    add_field_data(conn, Category.__table__, 'category_id', 2, 'category_alias', 'museums')
    add_field_data(conn, Category.__table__, 'category_id', 3, 'category_alias', 'theaters')
    add_field_data(conn, Category.__table__, 'category_id', 4, 'category_alias', 'history')
    add_field_data(conn, Category.__table__, 'category_id', 5, 'category_alias', 'cafe')
    add_field_data(conn, Category.__table__, 'category_id', 6, 'category_alias', 'hotels')
    add_field_data(conn, Category.__table__, 'category_id', 7, 'category_alias', 'persons')
    add_field_data(conn, Category.__table__, 'category_id', 8, 'category_alias', 'religion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'place', type_='foreignkey')
    op.drop_column('category', 'category_alias')
    # ### end Alembic commands ###
